Refactor2
Ethan-Lambourne/stockManagement pull request #3
Opened 2023-08-30 11:04 UTC by EL588

Using properties rather than fields within my objects, changed the items class to abstract, removed unnecessary assignment of values within some methods, attempted to put as much user interaction within the main program class as possible, and added a new class to handle displaying stock and report details to the console.

2023-08-30 13:28 UTC, HarryAmmon requested changes

2023-08-30 13:28 UTC, HarryAmmon commented on stockManagement/Program.cs
> +    foreach (Items item in ItemList)
It would probably be simpler to calculate all the totals at the time the report is created, rather than having a running total that you have to clear and recalculate every time the user does an action, even if it doesn't impact the total of laptops available, for example

2023-08-31 16:01 UTC, HarryAmmon commented on stockManagement/Program.cs
> +    if (check == false)
A neater way of doing this would be to check the number of items in the collection and if zero, display an error message

2023-09-01 08:29 UTC, EL588 commented on stockManagement/Program.cs
> +            displayDetail.laptopStock = displayDetail.laptopStock + item.Stock;
`displayDetail.laptopStock` is the total amount of laptops that are in stock, whereas `item.Stock` is just the amount of stock within a single item. So i'm not 100% sure how I could just use `item.Stock` for this?

2023-09-01 08:50 UTC, AlexBeesley requested changes

2023-09-01 10:54 UTC, merged