Repository Pattern Update
Ethan-Lambourne/stockManagement pull request #5
Opened 2023-09-05 09:20 UTC by Ethan-Lambourne

Tried my best to implement a repository pattern using a generic interface, ended up having to split my list of items into two separate lists, meaning I had to redo how I calculated and displayed the items in stock.

2023-09-05 09:44 UTC, AlexBeesley requested changes
Good work, my comments on the GraphicsCardRepo also apply for the laptop one. 

Consider structuring your project with folders (and namespaces to reflect that) so your models go in a models folder, your interface and repos go in a repos folder etc, everything but Program should be in folders.

2023-09-05 09:44 UTC, AlexBeesley commented on stockManagement/GraphicsCardRepository.cs
> +                    Console.WriteLine($"\nWhat would you like to edit about \"{item.Name}\"?" +
Get these values from the Program.cs, then pass them to this method as arguments, keep all user/console interactions in the program class.

2023-09-05 09:44 UTC, AlexBeesley commented on stockManagement/GraphicsCardRepository.cs
> +                            break;
the use of `break` isn't best practice, best avoided, use a `return` statement instead.

2023-09-05 09:44 UTC, AlexBeesley commented on stockManagement/GraphicsCardRepository.cs
> +                GraphicsCard NewItem = new GraphicsCard(newName, newType, newStock, newPrice, newVRAMamount, newCudaCores);
you shouldn't have to make a new one and delete the old one, you can directly assign to `item.Name` for example like: `item.Name = newName`

2023-09-05 09:44 UTC, AlexBeesley commented on stockManagement/GraphicsCardRepository.cs
> +        public void EditItem(string itemName)
you should return either a boolean or the instance of the item updated. same for delete.

2023-09-06 08:59 UTC, HarryAmmon requested changes
This is a good first attempt at the repository pattern, Ethan. 

I have left some comments of my own that should be responded to as well as Alex's'.

2023-09-06 08:59 UTC, HarryAmmon commented on stockManagement/IItemsRepository.cs
> +        void AddItem(T item);
It's normally best practice to return the item `T` after you have saved to your list/ file/ DB etc. This is because as part of the save you may add or change properties, normally IDs. It's consumer would probably find knowing what that information is helpful. 

For example, with the added the ID the consumer then knows what ID the item it just created has, so it can do further actions with it

2023-09-06 08:59 UTC, HarryAmmon commented on stockManagement/IItemsRepository.cs
> +        void EditItem(string itemName);
With edit, it doesn't hurt to return `T?` so we know what the updated item looks like and if the update was successful or not

2023-09-06 08:59 UTC, HarryAmmon commented on stockManagement/LaptopRepository.cs
> +        public void DeleteItem(string itemName)
We should search of items by an `ID` instead of an `itemName`. An ID will be unique to one particular item where as multiple pieces of stock could have the same name. Think of what what Apple (and others) do with their laptops. A search for "Macbook Pro 14" would return multiple years worth of products with wildly different specs, how would you know what one the user inteded to get/ delete/ update

2023-09-06 08:59 UTC, HarryAmmon commented on stockManagement/LaptopRepository.cs
> +                Console.WriteLine("\nItem removed.");
Any user I/O should be done in the program class. The repository class should be responsible for dealing with the collection of items only. What if you wanted to reuse this class as part of an API? The user would not be able to see the console. If you want to respond to if an action was successful, think about the `return` type

2023-09-06 08:59 UTC, HarryAmmon commented on stockManagement/LaptopRepository.cs
> +            var obj = LaptopList.FirstOrDefault(item => item.Name == itemName);
Try to use more descriptive variable names, even if it's obvious. Here a better name would be `laptop`

2023-09-06 16:01 UTC, merged