General Improvements
Ethan-Lambourne/stockManagement pull request #6
Opened 2023-09-06 16:07 UTC by Ethan-Lambourne

Restructured my program files into folders, moved a large amount of user interaction into the `Program.cs` file, reworked how I edited existing items, made my methods return either the item or a boolean value, added IDs to my items and made my `GetItem()` methods search for IDs rather than names, made some variable names more descriptive.

2023-09-08 09:50 UTC, HarryAmmon commented on stockManagement/Details/AddDetail.cs
> +        public readonly LaptopRepository _laptopRepository;
These should be private

2023-09-08 09:52 UTC, HarryAmmon commented on stockManagement/Repos/GraphicsCardRepository.cs
> +        public List<GraphicsCard> GraphicsCardList = new()
This list should be private

2023-09-19 09:48 UTC, HarryAmmon commented on stockManagement.Tests/Repos/GraphicsCardRepositoryTests.cs
> +            var graphicsCardRepository = new Mock<GraphicsCardRepository>();
Here we are testing the `GraphicsCardRepository` class which doesn't have any dependencies so mocking is not required here.

Tests should be run directly against an instance of the class we want to test, here you would create an new instance of the `GraphicsCardRepository` and call the `.Add` method.

```csharp
var graphicsCardRepository = new GraphicsCardRepository();

// Act
var check = graphicsCardRespotory.AddItem(item);
```

2023-09-19 10:05 UTC, AlexBeesley requested changes

2023-09-19 10:05 UTC, AlexBeesley commented on stockManagement.Tests/Repos/LaptopRepositoryTests.cs
> +        [Test]
To enhance your unit tests and give yourself more coverage look into the `TestCase` attribute.

2023-09-19 10:05 UTC, AlexBeesley commented on stockManagement.Tests/Repos/LaptopRepositoryTests.cs
> +            var item = new Laptop(999, "test laptop", "laptop", 11, 22.22, 33.33, 44, 55);
You are creating this laptop instance in every test, to avoid repetition, move this to the class level where a single instance can be used across all tests.

2023-09-19 10:35 UTC, HarryAmmon requested changes

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement.Tests/Repos/GraphicsCardRepositoryTests.cs
This is a good article to read on testing with collections

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement.Tests/Repos/GraphicsCardRepositoryTests.cs
> +            bool check = graphicsCardRepository.Object.DeleteItem(999);
Simpler to have this as `var` instead of `bool`

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement.Tests/stockManagement.Tests.csproj
Project and solution names should follow `PascalCase`

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement/Repos/IItemsRepository.cs
> +        T EditItem(T item, string newName, int newStock, double newPrice, double newScreenSize, int newRAMamount,
Think about the `Edit` function here. A method to update the details of a graphics card should not have the option to update the screen size. Think about what could be done with generics here

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement/Repos/LaptopRepository.cs
> +            if (newStock != 0) { item.Stock = newStock; }
The stock value could be 0, as well as the price

2023-09-19 10:35 UTC, HarryAmmon commented on stockManagement/Repos/LaptopRepository.cs
> +            if (laptop != null)
This can be simplified by returning the result of `FirstOrDefault`

2023-09-20 13:22 UTC, HarryAmmon requested changes

2023-09-20 13:22 UTC, HarryAmmon commented on stockManagement/Details/DisplayDetails.cs
> +            foreach (Laptop item in _laptopRepository.GetAllItems())
The display values class is kind of doing 2 things, generating the total of values and outputting values. These responsibilities should be separated into their own class.

As the `CalculateStocksAndValues()` method assigns the results of it's calculations to public fields, there is a chance that a consuming class might get the values from the fields without first calling `CalculateStockAndValues()` which would give them inaccurate data.

This method should be split into various methods and that be the only way to calculate the quantity or value or a collection of items. This value should be accessed by the return value of the method. You might want to use your experience with Generics to create a solution that works for both Graphic Cards and Laptops.

Any new classes should implement an interface and have unit tests to validate their behaviour.

2023-09-20 13:22 UTC, HarryAmmon commented on stockManagement/Details/AddDetail.cs
> +        public int GenerateID()
If you find this class has dependencies on other classes, you should mock these out using `Moq` as part of your unit tests

2023-10-03 08:41 UTC, HarryAmmon approved these changes

2023-10-03 08:48 UTC, merged