MVC Update
Ethan-Lambourne/StockManagement pull request #9
Opened 2023-12-18 16:35 UTC by Ethan-Lambourne

Added MVC functionality along with new tests for the controllers within it

2023-12-19 16:45 UTC, HarryAmmon requested changes

2023-12-19 16:45 UTC, HarryAmmon commented on StockManagement.MVC/Views/DeleteItem/DeleteItemView.cshtml
> +                    if (Model.Type == "laptop")
could use `typeof()` here instead of relying on literals

2024-01-05 15:01 UTC, HarryAmmon commented on StockManagement.MVC/Controllers/AddItemController.cs
> +                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = true, itemRecentlyEdited = false, itemRecentlyDeleted = false });
Better to use `HomeViewModel` here instead of creating an new object as you get type checking

2024-01-05 15:37 UTC, Ethan-Lambourne commented on StockManagement.MVC/Controllers/AddItemController.cs
> +                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = true, itemRecentlyEdited = false, itemRecentlyDeleted = false });
I just attempted this but kept running into errors because I completely forgot that the 3rd parameter for the `RedirectToAction` method is the route values taken by the `Index` method within the HomeController, and not the View Model

2024-02-09 16:13 UTC, merged